// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolDemo.Data;

namespace SchoolDemo.Migrations
{
  [DbContext(typeof(SchoolDbContext))]
  [Migration("20210125064251_reqname")]
  partial class reqname
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .UseIdentityColumns()
          .HasAnnotation("Relational:MaxIdentifierLength", 128)
          .HasAnnotation("ProductVersion", "5.0.2");

      modelBuilder.Entity("SchoolDemo.Models.Student", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint")
                      .UseIdentityColumn();

            b.Property<DateTime>("DateOfBirth")
                      .HasColumnType("datetime2");

            b.Property<string>("FirstName")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("LastName")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("Students");
          });
#pragma warning restore 612, 618
    }
  }
}
