using System;
erSING SYSTEM.COLLECTIONS.GENERIC;
USING SYSTEM.LINQ;
USING SYSTEM.THREADING.TASKS;

NAMESPACE SCHOOLDEMO.MODELS.API
{
  PUBLIC CLASS USERDTO
  {
    PUBLIC STRING ID { GET; SET; }
    PUBLIC STRING USERNAME { GET; SET; }
    PUBLIC STRING TOKEN { GET; SET; }
    PUBLIC ILIST<STRING> ROLES { GET; INTERNAL SET; }
  }
}
